help_notes = {
'main': [
'',
'List of available commands:',
'',
'create scheduler    Generate a scheduler with all elements.',
'create job          Generate a job with all elements.',
'list jobs           Show all jobs registered in the schedule.',
'edit schedule       Open the schedule file in the editor.',
'',
'edit job            Open the job script in the editor.',
'run job             Execute the job by id with or without run time.',
'run jobs            Execute the jobs listed in the file.',
'delete job          Delete the job by id.',
'',
'edit config         Open one of the configuration files in the editor',
'',
'help                Show this message.',
'',
'For more details type [command] help.',
],
'create_scheduler': [
'',
'Generate a scheduler with all elements.',
],
'create_job': [
'',
'Generate a job with all elements.',
'',
'NAME - technical name. Use default or enter any desired.',
'DESCRIPTION - short description. Enter any desired or leave empty.',
'ENVIRONMENT - used environment for execution. Choose from the list of',
'pointed in the main config.',
'',
'MONTH_DAY - day of month in range 1-31.',
'WEEK_DAY - day of week in range 1-7.',
'HOUR - hour of day in range 0-23.',
'MINUTE - minute of hour in range 0-59.',
'SECOND - second of minute in range 0-59',
'',
'STATUS - Y for active, N for inactive. Jobs with N status are skipped by',
'scheduler and not executed.',
'',
'You can schedule jobs by manipulating with time fields next few ways:',
'1. Execute job at certain date and time.',
'   Time presented as integers.',
'   Job that must be executed every day at 23:59:59 must look like:',
'   --------------------',
'   |HOUR|MINUTE|SECOND|',
'   --------------------',
'   |23  |59    |59    |',
'',
'2. Execute job every time cycle.',
'   Time presented as integers starting with /.',
'   Job that must be executed every 5 minutes must look like:',
'   ---------------',
'   |MINUTE|SECOND|',
'   ---------------',
'   |/5    |0     |',
'',
'3. Execute job only during certain period.',
'   Time presented as integers going with commas or dash.',
'   Job that must be executed only at weekdays at 23:59:59 must look like:',
'   -----------------------------',
'   |WEEK_DAY|HOUR|MINUTE|SECOND|',
'   -----------------------------',
'   |1-5     |23  |59    |59    |',
'',
'   Job that must be executed only at Monday, Wednesday, Friday at 23:59:59',
'   must look like:',
'   -----------------------------',
'   |WEEK_DAY|HOUR|MINUTE|SECOND|',
'   -----------------------------',
'   |1,3,5   |23  |59    |59    |',
'',
'You can combine different types of record.',
],
'list_jobs': [
'',
'Show all jobs registered in the schedule.',
'Parameters:',
'active      Show all jobs with status - Y.',
'inactive    Show all jobs with status - N.',
],
'edit_schedule': [
'',
'Open the schedule file in the editor.'
],
'edit_job': [
'',
'Open the job script in the editor.',
'Parameters:',
'id  integer  Id of the job you want to edit.',
],
'run_job': [
'',
'Execute the job by id with or without run time.',
'Parameters:',
'id         integer                  Id of the job you want to run.',
'trigger    yyyy-mm-dd/hh24:mi:ss    Date with or without time in ISO format',
'           yyyy-mm-dd               for what you want to run the job.',
'',
],
'run_jobs': [
'',
'Execute the jobs listed in the file.',
'Parameters:',
'file    path to file where each row is an id and a trigger for certain job',
'        separated with a space.',
'',
],
'delete_job': [
'',
'Delete the job by id.',
'Parameters:',
'id    integer    Id of the job you want to delete.',
],
'edit_config': [
'',
'Open one of the configuration files in the editor.',
'Parameters:',
'No        open config.ini',
'job id    open job.ini for job with id',
],
}
